# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
