# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20170508_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='owner',
        ),
    ]
